#!/usr/bin/perl -w

use strict;
use DBI;
use MIME::Lite::TT::HTML;

# Variables

my $username =  ''; # needs to be changed when live
my $password =  '';  
my $email =  'myemail.com';  
my $database =  'mydb';  
my $server =  'myserver';  
my $data;
my $nettypes; 
my $hosts; 
my $networks; 
my $maxhosts = 0; 
my $allocated = 0; 
my $counter = 0; 
my $availips = 0; 

# Arrays
my @row = ();
my @nid = ();
my @netrow = ();
my @ipcounts = (0) x 11;

my $dbh = DBI->connect("DBI:mysql:$database;host=$server", $username, $password)
    || die "Could not connect to database: $DBI::errstr";
my $cnames = $dbh->prepare('select * from cluster')
    || die "Could not connect to database: $DBI::errstr";  
$cnames->execute();

if ($cnames->rows < 0) {
    print "Error: no rows found.";
} else {
    $nettypes = $dbh->prepare('select * from networktype where cluster = ?')
        || die "Could not connect to database: $DBI::errstr";
    $networks = $dbh->prepare('select * from network where id = ?')
        || die "Could not connect to database: $DBI::errstr";
    $hosts = $dbh->prepare('select * from host where netid = ?')
        || die "Could not connect to database: $DBI::errstr";
    while (@row = $cnames->fetchrow_array()) {
        $nettypes->execute($row[0]);
        if ($nettypes->rows > 0) {
            while (@nid = $nettypes->fetchrow_array()) {
                if ($nid[1] eq 'shared-cloud') {
                    $networks->execute($nid[0]);
                    $hosts->execute($nid[0]);
                    @netrow = $networks->fetchrow_array();
                    $maxhosts = ($netrow[3] - $netrow[2]) + 1;
                    $allocated = $hosts->rows;
                    $availips += ($maxhosts - $allocated);
                }
            }
            $ipcounts[$counter] = $availips; 
            $counter++;
            $availips = 0;
        }
    }
    $counter = 0;
    $cnames->execute();
    $data = '<html><body><table border = "1"><tr><td><b>Cluster</b></td><td><b>Available IPs</b></td></tr>';
    while (@row = $cnames->fetchrow_array()) {
       $data =  $data . "<tr><td>$row[1]</td><td>$ipcounts[$counter]</td></tr>"; 
       $counter++;
    }
    $data =  $data . '</table></body></html>';
    my $footer = 'This automated message was generated by a script querying the IP database on <my database>. This message is sent daily at 7am EST.';
    my $msg = MIME::Lite->new(
               From      => 'services@services.com',
               To        => $email, 
               Type      => 'text/html',   
               Subject   => 'Cluster IPs available',
               Data      => $data, 
    );
    $msg->send;
}

# Disconnect
$cnames->finish;
$nettypes->finish;
$networks->finish;
$hosts->finish;
$dbh->disconnect;
